## 1. CSV 파일 불러와 DataFrame으로 저장

In [1]:
import pandas as pd
movies = pd.read_csv("./dataset/tmdb_5000_movies.csv")         # tmdb_5000_movies.csv dataframe으로 읽어오기
movies = movies[["id","genres","vote_average","vote_count","popularity","original_title", "keywords","overview"]]
movies["overview"] = movies["overview"].astype("str")
movies

,id,genres,vote_average,vote_count,popularity,original_title,keywords,overview
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",7.2,11800,150.437577,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",6.9,4500,139.082615,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.3,4466,107.376788,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",7.6,9106,112.312950,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.1,2124,43.926995,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4798,9367,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",6.6,238,14.269792,El Mariachi,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...
4799,72766,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",5.9,5,0.642552,Newlyweds,[],A newlywed couple's honeymoon is upended by th...
4800,231617,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",7.0,6,1.444476,"Signed, Sealed, Delivered","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,126186,[],5.7,7,0.857008,Shanghai Calling,[],When ambitious New York attorney Sam is sent t...
4802,25975,"[{""id"": 99, ""name"": ""Documentary""}]",6.3,16,1.929883,My Date with Drew,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...

## 2. 전처리

In [2]:
# null 값 개수 확인
movies.isnull().sum()

id                0
genres            0
vote_average      0
vote_count        0
popularity        0
original_title    0
keywords          0
overview          0
dtype: int64

### - 불공정 처리: weighted rating(https://www.quora.com/How-does-IMDbs-rating-system-work)   
WR=(v/(v+m))R+(m/(v+m))C\
r: 개별 영화 평점\
v:개별 영화에 평점을 투표한 횟수\
m: 250위 안에 들어야 하는 최소 투표(사용자 지정)\
c: 전체 영화에 대한 평균 평점

m을 500으로 설정하고 진행

In [3]:
m=movies['vote_count'].quantile(0.9)
movies=movies.loc[movies['vote_count']>=m]

In [4]:
movies

,id,genres,vote_average,vote_count,popularity,original_title,keywords,overview
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",7.2,11800,150.437577,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",6.9,4500,139.082615,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.3,4466,107.376788,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",7.6,9106,112.312950,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.1,2124,43.926995,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4291,176,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 9648, ""n...",7.2,2184,63.655973,Saw,"[{""id"": 1366, ""name"": ""shotgun""}, {""id"": 13000...",Obsessed with teaching his victims the value o...
4300,500,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 53, ""name...",8.0,3697,66.925866,Reservoir Dogs,"[{""id"": 2052, ""name"": ""traitor""}, {""id"": 6099,...",A botched robbery indicates a police informant...
4302,429,"[{""id"": 37, ""name"": ""Western""}]",8.1,2311,88.377076,"Il buono, il brutto, il cattivo","[{""id"": 801, ""name"": ""bounty hunter""}, {""id"": ...",While the Civil War rages between the Union an...
4337,103,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",8.0,2535,58.845025,Taxi Driver,"[{""id"": 422, ""name"": ""vietnam veteran""}, {""id""...",A mentally unstable Vietnam War veteran works ...
4602,389,"[{""id"": 18, ""name"": ""Drama""}]",8.2,2078,59.259204,12 Angry Men,"[{""id"": 934, ""name"": ""judge""}, {""id"": 1417, ""n...",The defense and the prosecution have rested an...

In [5]:
C=movies['vote_average'].mean()

In [6]:
print(C)
print(m)

6.9629937629937615
1838.4000000000015

In [7]:
def weighted_rating(x,m=m,C=C):
    v=x['vote_count']
    R=x['vote_average']
    
    return (v/(v+m)*R)+(m/(m+v)*C)

In [8]:
movies['score']=movies.apply(weighted_rating,axis=1)

<ipython-input-8-b8b8d42db16f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['score']=movies.apply(weighted_rating,axis=1)

In [9]:
movies.drop(['vote_average','vote_count','popularity','keywords'],axis=1,inplace=True)
movies.head()

C:\Users\SM-PC\anaconda3\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,id,genres,original_title,overview,score
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,"In the 22nd century, a paraplegic Marine is di...",7.168053
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",6.918271
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,A cryptic message from Bond’s past sends him o...,6.493333
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,Following the death of District Attorney Harve...,7.492998
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,"John Carter is a war-weary, former military ca...",6.500396

"overview" column 모두 소문자로, 문자+숫자(\w)만 남기고 나머지는 띄어쓰기로 대체\
https://wikidocs.net/21703 참고

In [10]:
import re
movies['overview'].apply(lambda x:re.sub('\W',' ',x.lower()))

0       in the 22nd century  a paraplegic marine is di...
1       captain barbossa  long believed to be dead  ha...
2       a cryptic message from bond s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war weary  former military ca...
                              ...
4291    obsessed with teaching his victims the value o...
4300    a botched robbery indicates a police informant...
4302    while the civil war rages between the union an...
4337    a mentally unstable vietnam war veteran works ...
4602    the defense and the prosecution have rested an...
Name: overview, Length: 481, dtype: object

TF-IDF 사용\
=>텍스트를 수치화한다 by 특징 추출\
가장 기본은 countVectorizer. 하지만 조사, 관사 등 **의미 없는 단어에 높은 수치를 부여** 할 위험이 있음\
https://chan-lab.tistory.com/24?category=810217 참고

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
# 단어 묶음을 1-2개로 설정
# ex) go home, very nice 등과 같은 단어도 인덱스로 받는다
tfidf_vec = TfidfVectorizer(ngram_range=(1, 2))
tfidf_matrix = tfidf_vec.fit_transform(movies['overview'])# 단어 학습

## cosine similarity

In [12]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
print("tfidf_matrix shape: ",tfidf_matrix.shape) # (데이터 개수, unique한 단어 개수)
plot_similarity = cosine_similarity(tfidf_matrix,tfidf_matrix) # 줄거리 간 cosine 유사도 구하기 - tfidf_matrix 사용
print("### COSINE Similarity ###")
print(plot_similarity)

tfidf_matrix shape:  (481, 24756)
### COSINE Similarity ###
[[1.         0.02099698 0.00887895 ... 0.01932427 0.0107505  0.02197317]
 [0.02099698 1.         0.01669792 ... 0.00894003 0.00897398 0.0259357 ]
 [0.00887895 0.01669792 1.         ... 0.01325899 0.00527382 0.01198323]
 ...
 [0.01932427 0.00894003 0.01325899 ... 1.         0.01624148 0.03342398]
 [0.0107505  0.00897398 0.00527382 ... 0.01624148 1.         0.0123923 ]
 [0.02197317 0.0259357  0.01198323 ... 0.03342398 0.0123923  1.        ]]